version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-springbatchm2e
    hostname: mongodb
    restart: on-failure
    environment:
      - MONGO_INITDB_DATABASE=demo
    ports:
      - "27017:27017"
    healthcheck:
      test: mongo --eval "rs.initiate()"
      interval: 10s
      start_period: 30s
    command: "--bind_ip_all --replSet rs0"
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    container_name: elastic-springbatchm2e
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
    ulimits:
      memlock:
        soft: -1
        hard: -1